Diplom_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from Diplom_project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('WeatherApp.urls')),
    path('Search/', include('Search.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Search/urls.py
from django.urls import path
from . import views

app_name = 'Search'
urlpatterns = [
    path('', views.index, name='index'),
]

WeatherApp/urls.py
from django.urls import path
from . import views

app_name = 'Weatherapp'
urlpatterns = [
    path('', views.index, name='home'),
    path('delete/<city_name>/', views.delete_city, name='delete_city'),

]

Search/models.py
from django.db import models

# Create your models here.

WeatherApp/models.py
from django.db import models


class City(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'cities'

WeatherApp/forms.py
from .models import City
from django.forms import ModelForm, TextInput


class CityForm(ModelForm):

    class Meta:
        model = City
        fields = ['name']
        widgets = {'name': TextInput(attrs={
            'class': 'form-control',
            'name': 'city',
            'id': 'city',
            'placeholder': 'Введите город'
        })}

Search/views.py
import requests

from isodate import parse_duration

from django.conf import settings
from django.shortcuts import render, redirect


def index(request):
    videos = []

    if request.method == 'POST':
        search_url = 'https://www.googleapis.com/youtube/v3/search'
        video_url = 'https://www.googleapis.com/youtube/v3/videos'

        search_params = {
            'part': 'snippet',
            'q': request.POST['search'],
            'key': settings.YOUTUBE_DATA_API_KEY,
            'maxResults': 20,
            'type': 'video'
        }

        r = requests.get(search_url, params=search_params)

        results = r.json()['items']

        video_ids = []
        for result in results:
            video_ids.append(result['id']['videoId'])

        if request.POST['submit'] == 'lucky':
            return redirect(f'https://www.youtube.com/watch?v={video_ids[0]}')

        video_params = {
            'key': settings.YOUTUBE_DATA_API_KEY,
            'part': 'snippet,contentDetails',
            'id': ','.join(video_ids),
            'maxResults': 9
        }

        r = requests.get(video_url, params=video_params)

        results = r.json()['items']

        for result in results:
            video_data = {
                'title': result['snippet']['title'],
                'id': result['id'],
                'url': f'https://www.youtube.com/watch?v={result["id"]}',
                'duration': int(parse_duration(result['contentDetails']['duration']).total_seconds() // 60),
                'thumbnail': result['snippet']['thumbnails']['high']['url']
            }

            videos.append(video_data)

    context = {
        'videos': videos
    }

    return render(request, 'search/index.html', context)

WeatherApp/views.py
from django.shortcuts import render, redirect
import requests
from .models import City
from .forms import CityForm


def index(request):
    appid = '9b185a328e000dbbd9255ab086904cc9'
    url = 'https://api.openweathermap.org/data/2.5/weather?q={}&units=metric&appid=' + appid + '& lang =ru'

    err_msg = ''
    message = ''
    message_class = ''

    if request.method == 'POST':
        form = CityForm(request.POST)

        if form.is_valid():
            new_city = form.cleaned_data['name']
            existing_city_count = City.objects.filter(name=new_city).count()

            if existing_city_count == 0:
                r = requests.get(url.format(new_city)).json()

                if r['cod'] == 200:
                    form.save()
                else:
                    err_msg = 'Город не найден!'
            else:
                err_msg = 'Город уже есть в базе!'

        if err_msg:
            message = err_msg
            message_class = 'is-danger'
        else:
            message = 'Город успешно добавлен!'
            message_class = 'is-success'

    form = CityForm()

    cities = City.objects.all()

    all_cities = []

    for city in cities:
        res = requests.get(url.format(city.name)).json()
        city_info = {
            'city': city.name.title(),
            'temp': res['main']['temp'],
            'hum': res['main']['humidity'],
            'wind': res['wind']['speed'],
            'icon': res['weather'][0]['icon']
        }
        all_cities.append(city_info)
    context = {'all_info': all_cities, 'form': form, 'message': message, 'message_class': message_class}
    return render(request, 'weatherapp/index.html', context)


def delete_city(request, city_name):
    City.objects.get(name=city_name).delete()
    return redirect('Weatherapp:home')

templates/search/index.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>YouTube</title>
    <style>
        body {background-image: url({% static "1.jpg"%}); background-size: 100hv; background-attachment: fixed;}
    </style>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="shortcut icon" href='/static/2.png' type="image/x-icon">
</head>
<body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal">Дипломный проект</h5>
        <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-dark" href="{% url 'admin:index' %}">Панель администратора</a>
            <a class="p-2 text-dark" href="{% url 'Weatherapp:home' %}">Погодное приложение</a>
        </nav>
        <a class="btn btn-outline-primary" href="https://developers.google.com/youtube/v3">Документация</a>
    </div>

<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">YouTube поиск</h1>
      <p class="lead text-muted">Получить 20 результатов соответствующих запросу!</p>
      <form method="POST">
      <div class="input-group mb-3">
          {% csrf_token %}
          <input type="text" name="search" class="form-control" aria-label="Username">
      </div>
      <p>
        <button type="submit" name="submit" value="search" class="btn btn-primary my-2">Поиск</button>
        <button type="submit" name="submit" value="lucky" class="btn btn-secondary my-2">Мне повезет</button>
      </p>
      </form>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        {% for video in videos %}
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="{{ video.thumbnail }}"
                 preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail">
            <div class="card-body">
              <p class="card-text">{{ video.title }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a type="button" href="{{ video.url }}" class="btn btn-sm btn-outline-secondary">Смотреть</a>
                </div>
                <small class="text-muted">{{ video.duration }} мин</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

</main>
</body>
</html>

templates/weatherapp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Погодное приложение</title>
    <style>
        body {background-image: url({% static "1.jpg"%}); background-size: 100hv; background-attachment: fixed;}
    </style>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="shortcut icon" href="https://cdn3.iconfinder.com/data/icons/bebreezee-weather-symbols/691/icon-weather-sunsleetlight-512.png" type="image/x-icon">
</head>
<body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal">Дипломный проект</h5>
        <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-dark" href="{% url 'admin:index' %}">Панель администратора</a>
            <a class="p-2 text-dark" href="{% url 'Search:index' %}">YouTube поиск</a>
        </nav>
        <a class="btn btn-outline-primary" href="https://openweathermap.org/">Документация</a>
    </div>
    <div class="container mt-5">
        <div class="row">
            <div class="col-5 offset-1">
                <h1>Погода в вашем городе</h1>
                <form action="" method="post">
                    {% csrf_token %}
                    <label for="city"></label>
                    {{ form.name }}
                    <input type="submit" name="send" value="Узнать" class="btn btn-primary my-2">
                    {% if message %}
                        <div class="notification {{ message_class }}">{{ message }}
                            <button class="close" aria-label="Close"
                                    onclick="document.getElementsByClassName('notification')[0].style.display='none'">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                </form>
            </div>
            <div class="col-4 offset-2">
                <h1>Информация</h1>

                {% for info in all_info %}
                <div class="alert alert-info">
                    <div class="row">
                        <div class="col-8">
                            <b>Город: </b>{{ info.city }}<br>
                            <b>Температура: </b>{{ info.temp }}<sup>o</sup><br>
                            <b>Влажность: </b>{{ info.hum }} %<br>
                            <b>Скорость ветра: </b>{{ info.wind }} м/с<br>
                        </div>
                        <td class="align-middle">
                            <div class="col-2">
                                <img src="http://openweathermap.org/img/w/{{ info.icon }}.png" alt="Фото погоды"
                                    class="mx-auto" style="width: 50px;">
                            </div>
                            <div class="col-2">
                                <a href="{% url 'Weatherapp:delete_city' info.city %}">
                                    <button type="button" class="close" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </a>
                            </div>
                        </td>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</body>
</html>